- Name: Abhay Kansal
  Email: abhay.kansalprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Bifrost
  Status: Active
  Github Account: abhaykansal177
  Slack Account: "U04MR5V960P"
- Name: Aman Gupta
  Email: aman.guptaprocol.in
  Designation: Product Design 1
  Department: Design
  Pod: Universe
  Status: Active
  Github Account: AmanProcol
  Slack Account: "U049612LE3E"
- Name: Apoorv Jain
  Email: apoorv.jainprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: apoorv-jain-0
  Slack Account: "U042N7QAYFJ"
- Name: Ayush Jaiswal
  Email: ayush.jaiswalprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Lighthouse
  Status: Active
  Github Account: AJ-Ayush
  Slack Account: "U04MZ3X8HAA"
- Name: Chaitanya Aditya
  Email: chaitanya.adityaprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: holaChaitanya
  Slack Account: "U028AQ88Q04"
- Name: Gaurav Thapar
  Email: gaurav.thaparprocol.in
  Designation: SDE 2
  Department: Engineering
  Pod: Bifrost
  Status: Active
  Github Account: thapargaurav
  Slack Account: "U01LAA0UPFY"
- Name: Gaurav Tiwari
  Email: gaurav.tiwariprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: tewarig
  Slack Account: "U04HKHZNL2J"
- Name: Harshit Chaudhary
  Email: harshit.chaudharyprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: harrrykp
  Slack Account: "U03KHDE6DRU"
- Name: Harshita Jain
  Email: harshita.jainprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Next Big Thing
  Status: Active
  Github Account: harshita-jain82
  Slack Account: "U04NJAZ5AKT"
- Name: Ishan Kumar
  Email: ishan.kumarprocol.in
  Designation: PM
  Department: Product
  Pod: Next Big Thing
  Status: Active
  Github Account: ishan180
  Slack Account: "U03MAHXMBK6"
- Name: Parth Batra
  Email: parth.batraprocol.in
  Designation: Data Science
  Department: Data Engineering
  Pod: "Dexter's Lab"
  Status: Active
  Github Account: dataguyofprocol
  Slack Account: "U01H8THV4BF"
- Name: Piyushh Bhutoria
  Email: piyushh.bhutoriaprocol.in
  Designation: SDE 2
  Department: Engineering
  Pod: Bifrost
  Status: Active
  Github Account: Piyushhbhutoria
  Slack Account: "U04LR1BK6TA"
- Name: Rahul Raj
  Email: rahul.rajprocol.in
  Designation: SDE 2
  Department: Engineering
  Pod: Next Big Thing
  Status: Active
  Github Account: damnitrahul
  Slack Account: "U01A3JTJFHT"
- Name: Richell Robin
  Email: richell.robinprocol.in
  Designation: APM
  Department: Product
  Pod: Next Big Thing
  Status: Active
  Github Account: Richell2405
  Slack Account: "U05D9RXRQT0"
- Name: Sakib Khan
  Email: sakib.khanprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: notSakib
  Slack Account: "U04CTTYB4EB"
- Name: Saksham Sharma
  Email: saksham.sharmaprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Next Big Thing
  Status: Active
  Github Account: saksham-procol
  Slack Account: "U02SUUU1K41"
- Name: Saumya Chauhan
  Email: saumya.chauhanprocol.in
  Designation: SDE 2
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: saumyachauhan12
  Slack Account: "U011NL4J1PT"
- Name: Shikhar Srivastava
  Email: shikhar.srivastavaprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: shikhars236
  Slack Account: "U03HBNWPKFH"
- Name: Shivam Chauhan
  Email: shivam.chauhanprocol.in
  Designation: SDE 2
  Department: Engineering
  Pod: Lighthouse
  Status: Active
  Github Account: shivamProcol
  Slack Account: "U01LP8AS3JQ"
- Name: Shivansh Gupta
  Email: shivansh.guptaprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Next Big Thing
  Status: Active
  Github Account: dope0403
  Slack Account: "U04MR5V92UF"
- Name: Sumit Mendiratta
  Email: sumitprocol.in
  Designation: Co-founder & CTO
  Department:
  Pod:
  Status: Active
  Github Account: sumitprocol
  Slack Account: "UPR929F0S"
- Name: Tanish Kumar
  Email: tanish.kumarprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Lighthouse
  Status: Active
  Github Account: tks3000
  Slack Account: "U032L1G3Q1E"
- Name: Tushar Garg
  Email: tushar.gargprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Next Big Thing
  Status: Active
  Github Account: tushar-procol
  Slack Account: "U04NVCKQZAL"
- Name: Vaidik Kapoor
  Email: vaidik.kapoorprocol.in
  Designation: Engineering Coach
  Department: Engineering
  Pod: Lighthouse
  Status: Active
  Github Account: vaidik
  Slack Account: "U05BNEKS3HN"
- Name: Yadu Singla
  Email: yadu.singlaprocol.in
  Designation: Tech Lead
  Department: Engineering
  Pod: Lighthouse
  Status: Active
  Github Account: yadusingla
  Slack Account: "U014WDV8C4Q"
- Name: Yash Sharma
  Email: yash.sharmaprocol.in
  Designation: SDE 1
  Department: Engineering
  Pod: Universe
  Status: Active
  Github Account: AshYash17
  Slack Account: "U04N5MJNSLA"
- Name: Yugandhar Bhamare
  Email: yugandhar.bhamareprocol.in
  Designation: Sr. PM
  Department: Product
  Pod: Universe
  Status: Active
  Github Account: yug-bhamare
  Slack Account: "U039N9N979R"
